[workspace]
resolver = "3"
members = [
    "subtest",
    "subtest-impl",
]

[workspace.dependencies]
subtest-impl = { path = "subtest-impl" }

proc-macro2 = "1.0.106"
quote = "1.0.46"
syn = { version = "2.0.118", features = ["full"] }
insta = { version = "1.48.0", features = ["glob"] }
prettyplease = "0.2.37"
macrotest = "1.2.1"
