[package]
name = "subtest-impl"
description = "Implementation detail of the `subtest` crate"
version = "0.0.1"
edition = "2024"
rust-version = "1.85"
authors = ["Nikolaus Thümmel <commit.nthuemmel@ntcomputer.de>"]
license = "MIT OR Apache-2.0"
homepage = "https://github.com/nthuemmel/subtest"
repository = "https://github.com/nthuemmel/subtest"

[dependencies]
quote = { workspace = true }
syn = { workspace = true }
proc-macro2 = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
prettyplease = { workspace = true }
