//! Code inherited by a subtest is copied out of its parent test function, carrying the spans of
//! the source it was written in. To the compiler it is therefore indistinguishable from code the
//! author wrote inside the subtest, which makes lints fire once per subtest inheriting it - on a
//! line the author cannot act on, because it belongs to the parent.
//!
//! Marking the inherited copies as generated by this macro stops that: `Span::call_site()` carries
//! the expansion this macro is, so the compiler knows the code did not appear literally where it
//! now stands. `located_at` keeps the original source location, so diagnostics which do survive
//! still point at the code the author wrote.

#![allow(
    dead_code,
    reason = "not wired into the inheritance of statements, parameters and return types yet"
)]

use proc_macro2::{Group, Span, TokenStream, TokenTree};
use quote::ToTokens;
use syn::parse::Parse;

pub trait Spanned {
    /// Mark every token of `self` as generated by this macro, keeping its source location
    ///
    /// # Panics
    ///
    /// If the marked tokens do not parse back into `Self`. Marking changes nothing but spans, so
    /// this can only happen for a type whose `Parse` implementation does not accept everything its
    /// `ToTokens` implementation spells out - notably [`syn::Stmt`], which spells out a trailing
    /// expression without a semicolon but refuses to parse one back. Mark the enclosing
    /// [`syn::Block`] instead of such a statement.
    fn mark_as_macro_generated(self) -> Self;
}

impl<T> Spanned for T
where
    T: ToTokens + Parse,
{
    fn mark_as_macro_generated(self) -> Self {
        let marked = mark_tokens_as_macro_generated(self.to_token_stream());

        // marking a token changes nothing but its span, so whatever parsed into `T` before still
        // parses into `T`
        syn::parse2(marked).expect("marking tokens must not change the syntax they spell out")
    }
}

/// Mark every token in the stream as generated by this macro, keeping its source location
fn mark_tokens_as_macro_generated(tokens: TokenStream) -> TokenStream {
    tokens
        .into_iter()
        .map(|token| match token {
            // a group's own span covers its delimiters only, so the tokens it encloses have to be
            // marked separately
            TokenTree::Group(group) => {
                let mut marked = Group::new(
                    group.delimiter(),
                    mark_tokens_as_macro_generated(group.stream()),
                );
                marked.set_span(macro_generated(group.span()));
                TokenTree::Group(marked)
            }

            mut other => {
                other.set_span(macro_generated(other.span()));
                other
            }
        })
        .collect()
}

/// The span of this macro's expansion, but pointing at the location `span` came from.
///
/// `Span::call_site()` resolves names as if the tokens were written at the macro call site, so
/// marked code still sees - and is seen by - the code surrounding it.
fn macro_generated(span: Span) -> Span {
    Span::call_site().located_at(span)
}

#[cfg(test)]
mod tests {
    use super::*;
    use quote::quote;
    use syn::{Block, Expr, ItemFn, ReturnType, Stmt, parse_quote};

    /// Spans take no part in syn's `PartialEq`, so this compares the syntax itself - which marking
    /// has to leave untouched. That the spans *are* marked cannot be observed from a unit test:
    /// outside a real macro expansion, `proc-macro2` falls back to an implementation in which
    /// `located_at` returns the original span unchanged. The macrotest fixtures cover the effect.
    fn assert_syntax_is_preserved<T>(node: &T)
    where
        T: Spanned + Clone + PartialEq + std::fmt::Debug,
    {
        assert_eq!(node.clone().mark_as_macro_generated(), *node);
    }

    #[test]
    fn mark_a_declaration() {
        let statement: Stmt = parse_quote!(let value = 1;);

        assert_syntax_is_preserved(&statement);
    }

    #[test]
    fn mark_a_declaration_without_a_value() {
        let statement: Stmt = parse_quote!(let value;);

        assert_syntax_is_preserved(&statement);
    }

    #[test]
    fn mark_a_declaration_with_attributes() {
        let statement: Stmt = parse_quote! {
            #[allow(unused_variables)]
            #[expect(unused_mut, reason = "a reason")]
            let (sender, mut receiver) = channel();
        };

        assert_syntax_is_preserved(&statement);
    }

    #[test]
    fn mark_an_expression_statement() {
        let statement: Stmt = parse_quote!(do_something(1, "two"););

        assert_syntax_is_preserved(&statement);
    }

    /// A trailing expression is a statement without a semicolon. `syn` spells one out but does not
    /// parse it back, so such a statement cannot be marked on its own - see
    /// `mark_a_block_with_a_trailing_expression` for the way around it.
    #[test]
    #[should_panic(expected = "marking tokens must not change the syntax they spell out")]
    fn mark_a_trailing_expression_on_its_own() {
        let block: Block = parse_quote!({ Ok(()) });
        let statement = block.stmts.into_iter().next().unwrap();

        assert!(matches!(statement, Stmt::Expr(_, None)));

        let _ = statement.mark_as_macro_generated();
    }

    /// Wrapped in its block, a trailing expression round trips - the block spells out its braces,
    /// which is what lets `syn` parse the statements within as a body rather than on their own
    #[test]
    fn mark_a_block_with_a_trailing_expression() {
        let block: Block = parse_quote!({
            let value = 1;
            Ok(())
        });

        assert_syntax_is_preserved(&block);
    }

    #[test]
    fn mark_a_nested_item() {
        let statement: Stmt = parse_quote! {
            fn helper(value: u32) -> u32 {
                value * 2
            }
        };

        assert_syntax_is_preserved(&statement);
    }

    #[test]
    fn mark_a_macro_statement() {
        let statement: Stmt = parse_quote!(assert_eq!(value, 1););

        assert_syntax_is_preserved(&statement);
    }

    #[test]
    fn mark_a_statement_with_deeply_nested_delimiters() {
        let statement: Stmt = parse_quote! {
            let value = {
                let inner = [(1, 2), (3, 4)];
                inner.iter().map(|(a, b)| vec![*a, *b]).collect::<Vec<_>>()
            };
        };

        assert_syntax_is_preserved(&statement);
    }

    #[test]
    fn mark_a_return_type() {
        let return_type: ReturnType = parse_quote!(-> anyhow::Result<()>);

        assert_syntax_is_preserved(&return_type);
    }

    /// A missing return type spells out no tokens at all, so it round trips through an empty stream
    #[test]
    fn mark_a_missing_return_type() {
        let return_type = ReturnType::Default;

        assert_syntax_is_preserved(&return_type);
    }

    #[test]
    fn mark_a_function() {
        let function: ItemFn = parse_quote! {
            #[test]
            fn a_test() -> Result<(), String> {
                let value = 1;
                assert_eq!(value, 1);
                Ok(())
            }
        };

        assert_syntax_is_preserved(&function);
    }

    #[test]
    fn mark_an_expression() {
        let expression: Expr = parse_quote!(if condition { one() } else { other() });

        assert_syntax_is_preserved(&expression);
    }

    #[test]
    fn mark_tokens_keeps_every_token_and_delimiter() {
        let tokens = quote! {
            let value = [ { (1) } ];
        };

        assert_eq!(
            mark_tokens_as_macro_generated(tokens.clone()).to_string(),
            tokens.to_string()
        );
    }

    #[test]
    fn mark_an_empty_token_stream() {
        assert!(mark_tokens_as_macro_generated(TokenStream::new()).is_empty());
    }
}
