#![allow(dead_code, reason = "wip")]

use proc_macro2::{Delimiter, Group, Span, TokenStream, TokenTree, token_stream};
use quote::ToTokens;
use syn::parse::Parse;

pub trait Spanned {
    /// Mark every token of `self` as generated by this macro, keeping its source location
    fn mark_as_macro_generated(self) -> Self;
}

impl<T> Spanned for T
where
    T: ToTokens + Parse,
{
    fn mark_as_macro_generated(self) -> Self {
        let marked = mark_tokens_as_macro_generated(self.to_token_stream());
        // Note: The following expect does not hold for trailing expression statements, like just
        // `Ok(())` - syn just refuses to parse that
        syn::parse2(marked).expect("parsing of unmodified emitted tokens should work")
    }
}

fn mark_tokens_as_macro_generated(tokens: TokenStream) -> TokenStream {
    struct Level {
        remaining: token_stream::IntoIter,
        marked: Vec<TokenTree>,
        group: Option<(Delimiter, Span)>,
    }

    let mut levels = vec![Level {
        remaining: tokens.into_iter(),
        marked: Vec::new(),
        group: None,
    }];

    loop {
        let level = levels
            .last_mut()
            .expect("the outermost level is only left by returning");

        match level.remaining.next() {
            // a group's own span covers its delimiters only, so its tokens must be marked
            // separately
            Some(TokenTree::Group(group)) => levels.push(Level {
                remaining: group.stream().into_iter(),
                marked: Vec::new(),
                group: Some((group.delimiter(), group.span())),
            }),

            Some(mut token) => {
                token.set_span(macro_generated(token.span()));
                level.marked.push(token);
            }

            // this level is done: close its group and hand it to the level below, or return if
            // there is none left to hand it to
            None => {
                let Level { marked, group, .. } =
                    levels.pop().expect("the level was just borrowed");

                let Some((delimiter, span)) = group else {
                    return marked.into_iter().collect();
                };

                let mut marked = Group::new(delimiter, marked.into_iter().collect());
                marked.set_span(macro_generated(span));

                levels
                    .last_mut()
                    .expect("a group was descended into from the level below it")
                    .marked
                    .push(TokenTree::Group(marked));
            }
        }
    }
}

/// The span of this macro's expansion, but pointing at the location `span` came from.
fn macro_generated(span: Span) -> Span {
    Span::call_site().located_at(span)
}

#[cfg(test)]
mod tests {
    use super::*;
    use quote::quote;
    use syn::{Block, Expr, ItemFn, ReturnType, Stmt, parse_quote};

    fn assert_correct_marking_as_macro_generated<T>(node: &T)
    where
        T: Spanned + ToTokens + Clone + PartialEq + std::fmt::Debug,
    {
        let marked = node.clone().mark_as_macro_generated();

        // syn's `PartialEq` only compares syntax, not spans
        assert_eq!(node.clone().mark_as_macro_generated(), *node);

        assert_locations_are_kept(node.to_token_stream(), marked.to_token_stream());

        // hygiene (call site vs definition site) is unobservable via syn's API,
        // so we cannot assert it
    }

    #[test]
    fn mark_a_declaration() {
        let statement: Stmt = parse_quote!(let value = 1;);

        assert_correct_marking_as_macro_generated(&statement);
    }

    #[test]
    fn mark_a_declaration_without_a_value() {
        let statement: Stmt = parse_quote!(let value;);

        assert_correct_marking_as_macro_generated(&statement);
    }

    #[test]
    fn mark_a_declaration_with_attributes() {
        let statement: Stmt = parse_quote! {
            #[allow(unused_variables)]
            #[expect(unused_mut, reason = "a reason")]
            let (sender, mut receiver) = channel();
        };

        assert_correct_marking_as_macro_generated(&statement);
    }

    #[test]
    fn mark_an_expression_statement() {
        let statement: Stmt = parse_quote!(do_something(1, "two"););

        assert_correct_marking_as_macro_generated(&statement);
    }

    #[test]
    fn mark_a_block_with_a_trailing_expression() {
        let block: Block = parse_quote!({
            let value = 1;
            Ok(())
        });

        assert_correct_marking_as_macro_generated(&block);
    }

    #[test]
    fn mark_a_nested_item() {
        let statement: Stmt = parse_quote! {
            fn helper(value: u32) -> u32 {
                value * 2
            }
        };

        assert_correct_marking_as_macro_generated(&statement);
    }

    #[test]
    fn mark_a_macro_statement() {
        let statement: Stmt = parse_quote!(assert_eq!(value, 1););

        assert_correct_marking_as_macro_generated(&statement);
    }

    #[test]
    fn mark_a_statement_with_deeply_nested_delimiters() {
        let statement: Stmt = parse_quote! {
            let value = {
                let inner = [(1, 2), (3, 4)];
                inner.iter().map(|(a, b)| vec![*a, *b]).collect::<Vec<_>>()
            };
        };

        assert_correct_marking_as_macro_generated(&statement);
    }

    #[test]
    fn mark_a_return_type() {
        let return_type: ReturnType = parse_quote!(-> anyhow::Result<()>);

        assert_correct_marking_as_macro_generated(&return_type);
    }

    #[test]
    fn mark_a_missing_return_type() {
        let return_type = ReturnType::Default;

        assert_correct_marking_as_macro_generated(&return_type);
    }

    #[test]
    fn mark_a_function() {
        let function: ItemFn = parse_quote! {
            #[test]
            fn a_test() -> Result<(), String> {
                let value = 1;
                assert_eq!(value, 1);
                Ok(())
            }
        };

        assert_correct_marking_as_macro_generated(&function);
    }

    #[test]
    fn mark_an_expression() {
        let expression: Expr = parse_quote!(if condition { one() } else { other() });

        assert_correct_marking_as_macro_generated(&expression);
    }

    /// Marking has to keep pointing at the source the token came from, so that diagnostics which
    /// survive it still name the line the author wrote. Parsing from a string is what gives the
    /// tokens a location in the first place - `quote!` builds them without one.
    #[test]
    fn mark_tokens_keeps_the_source_location_of_every_token() {
        let tokens: TokenStream = "let value = [ { (1) } ];".parse().unwrap();

        assert_locations_are_kept(tokens.clone(), mark_tokens_as_macro_generated(tokens));
    }

    fn assert_locations_are_kept(original: TokenStream, marked: TokenStream) {
        let original: Vec<TokenTree> = original.into_iter().collect();
        let marked: Vec<TokenTree> = marked.into_iter().collect();

        assert_eq!(
            original.len(),
            marked.len(),
            "marking dropped or added tokens"
        );

        for (original, marked) in original.into_iter().zip(marked) {
            assert_eq!(
                (marked.span().start(), marked.span().end()),
                (original.span().start(), original.span().end()),
                "marking lost the location of `{marked}`"
            );

            // the tokens a group encloses are marked separately from the group itself
            if let (TokenTree::Group(original), TokenTree::Group(marked)) = (original, marked) {
                assert_locations_are_kept(original.stream(), marked.stream());
            }
        }
    }

    #[test]
    fn mark_tokens_keeps_every_token_and_delimiter() {
        let tokens = quote! {
            let value = [ { (1) } ];
        };

        assert_eq!(
            mark_tokens_as_macro_generated(tokens.clone()).to_string(),
            tokens.to_string()
        );
    }

    /// Nesting is as deep as the code handed to the macro, which is why the levels are walked on
    /// a stack of their own - a depth like this overflows the call stack when recursing
    #[test]
    fn mark_tokens_of_deeply_nested_groups() {
        let mut tokens: TokenStream = "1".parse().unwrap();
        for _ in 0..100_000 {
            tokens =
                TokenTree::Group(Group::new(Delimiter::Parenthesis, tokens)).into_token_stream();
        }

        let marked = mark_tokens_as_macro_generated(tokens);

        // `to_string` would recurse through the groups, so the depth is counted on a stack as well
        let mut depth = 0_usize;
        let mut level = marked;
        loop {
            let Some(TokenTree::Group(group)) = level.into_iter().next() else {
                break;
            };

            depth += 1;
            level = group.stream();
        }

        assert_eq!(depth, 100_000);
    }

    #[test]
    fn mark_an_empty_token_stream() {
        assert!(mark_tokens_as_macro_generated(TokenStream::new()).is_empty());
    }
}
