fn main() {}

// `missing_fn()` is inherited by all six subtests below, yet the error is reported twice: once for
// the parent's own copy, and once for all inherited copies together. The macro marks inherited
// code as generated by a single expansion of itself, so every inherited copy carries the same
// macro context as well as the same source location - which makes the compiler collapse them into
// one diagnostic. The count therefore does not grow with the number of subtests.
#[subtest::subtest(allow_missing_test_attribute)]
fn parent() {
    missing_fn();

    #[subtest]
    fn first() {}

    #[subtest]
    fn second() {}

    #[subtest]
    fn third() {
        #[subtest]
        fn nested_in_third() {}

        #[subtest]
        fn also_nested_in_third() {}
    }

    #[subtest]
    fn fourth() {}
}
